source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LIHArcView_Example', :exclusive => true do
  pod 'LIHArcView', :path => '../'
end

target 'LIHArcView_Tests', :exclusive => true do
  pod 'LIHArcView', :path => '../'

  
end
